version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen-app
    volumes:
      - app-data:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  server:
    image: nginx:1-alpine
    container_name: lumen-server
    ports:
      - 8000:80
    volumes:
      - app-data:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: lumen-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: lumen-api-starter
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

volumes:
  db-data:
  app-data:
